Feature/footer
NeoZLoy/group-project-16 pull request #13
Opened 2023-04-08 18:08 UTC by OleksandrLukomskyi

2023-04-09 07:47 UTC, NeoZLoy requested changes

2023-04-09 07:47 UTC, NeoZLoy commented on src/css/partials/footer.css
>          gap: 124px;
Добавь justify-contnent: space-between; 
Это переместит элементы к краям секции

2023-04-09 07:47 UTC, NeoZLoy commented on src/css/partials/footer.css
>          gap: 124px;
если добавить justify-contnent: space-between - gap будет не нужен

2023-04-09 07:47 UTC, NeoZLoy commented on src/partials/footer.html
>    <div class="container container-bloc">
нужно убрать class="container" так как футер у нас тянется на всю ширину вьюпорта. 
оставь class="container-bloc" и задай ему ширину 100%

2023-04-09 07:47 UTC, NeoZLoy commented on src/css/partials/footer.css
>     padding-bottom: 32px;
так как мы зададим ширину 100%, понадобяться боковые паддинги по макету (в медиправилах тоже):
для моб: padding: 32px 20px;
для таб: padding: 50px 32px;
для деск остаются 50 и 32

2023-04-09 19:44 UTC, OleksandrLukomskyi commented on src/css/partials/footer.css
>          gap: 124px;
> justify-contnent: space-between;

Исправил

2023-04-09 19:46 UTC, OleksandrLukomskyi commented on src/css/partials/footer.css
>          gap: 124px;
> если добавить justify-contnent: space-between - gap будет не нужен

gap убрал

2023-04-09 19:53 UTC, OleksandrLukomskyi commented on src/css/partials/footer.css
>     padding-bottom: 32px;
> так как мы зададим ширину 100%, понадобяться боковые паддинги по макету (в медиправилах тоже): для моб: padding: 32px 20px; для таб: padding: 50px 32px; для деск остаются 50 и 32

Исправил

2023-04-10 08:09 UTC, NeoZLoy approved these changes
Всё отлично, но нет эффектов hove & focus на активных элементах. Чтобы было быстрее - я сам допилю, но в дальнейшем будь внимательнее)

2023-04-10 08:09 UTC, merged

2023-04-10 08:36 UTC, OleksandrLukomskyi commented
> Всё отлично, но нет эффектов hove & focus на активных элементах. Чтобы было быстрее - я сам допилю, но в дальнейшем будь внимательнее)

Хорошо.