Feature/subscribe modal 3
NeoZLoy/group-project-16 pull request #19
Opened 2023-04-09 16:05 UTC by OleksandrLukomskyi

2023-04-09 18:53 UTC, Anastasiia505 commented on src/partials/subscribe.html
>    </div>
В button додати клас js-open-modal та атрибут data-modal="3"

2023-04-09 19:16 UTC, NeoZLoy requested changes

2023-04-09 19:16 UTC, NeoZLoy commented on src/css/partials/subscribe.css
> +      height: 52px;
нужно добавть: `border:0;`

2023-04-09 19:53 UTC, Anastasiia505 commented on src/partials/subscribe.html
> +    <use href="../img/sprite.svg#icon-close-button"></use>
змінити назву кнопки #icon-close

2023-04-09 19:57 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +@media screen and (min-width: 768px) {
Добавить правило для мобайл версии кнопка должна быть размер 12х12

2023-04-09 20:06 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  width: 24px;
размеры кнопки 14х14
изменить в медиаправиле для мобайл размер 12х12

2023-04-09 20:07 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  stroke:var(--color-white);
Цвет кнопки закрытия белый через (fill)

2023-04-09 20:10 UTC, OleksandrLukomskyi commented on src/partials/subscribe.html
>    </div>
> В button додати клас js-open-modal та атрибут data-modal="3"

ДОДАВ

2023-04-09 20:12 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +input::placeholder{
не правильно задана команда, треба .input-mail-subscribe::placeholder

2023-04-09 20:14 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  @media screen and (min-width:768px) {
написано одно правила медиа несколько раз. Все команды которые относятся к одному медиаправилу нужно собрать в одном месте

2023-04-09 20:21 UTC, OleksandrLukomskyi commented on src/partials/subscribe.html
> +    <use href="../img/sprite.svg#icon-close-button"></use>
> #icon-close

в мене  в спрайті нема з такою назвою.

2023-04-09 20:22 UTC, Anastasiia505 commented on src/partials/subscribe.html
> +    <use href="../img/sprite.svg#icon-close-button"></use>
ти оновив main? (онови)

2023-04-09 20:24 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +@media screen and (min-width: 768px) {
> Добавить правило для мобайл версии кнопка должна быть размер 12х12

Виправив. Але всерівно х якийсь малий і щось заважае.

2023-04-09 20:29 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  border-radius: 100px;
додати border: 0;

2023-04-09 20:34 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +  stroke:var(--color-white);
> Цвет кнопки закрытия белый через (fill)

 svg з спрайта  #icon-close-button  не видно через  (fill).  #icon-close такого нема в спрайте.

2023-04-09 20:36 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +@media screen and (min-width: 768px) {
я вже не побачу, треба заново комітити. що саме заважає?

2023-04-09 20:37 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +input::placeholder{
> .input-mail-subscribe::placeholder

Виправив

2023-04-09 20:37 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  stroke:var(--color-white);
вже є треба оновити main, треба через fill

2023-04-09 20:40 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +  @media screen and (min-width:768px) {
> написано одно правила медиа несколько раз. Все команды которые относятся к одному медиаправилу нужно собрать в одном месте

Не обов'язково.  Мені так показали в попередній групі. Щоб не згубити нічого.

2023-04-09 20:42 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  @media screen and (min-width:768px) {
ок

2023-04-09 20:43 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +  border-radius: 100px;
> додати border: 0;

додав

2023-04-09 20:44 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +      height: 52px;
> нужно добавть: `border:0;`

додав

2023-04-09 21:14 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  /* opacity: 0;
прибери комент цей, бо вікно не ховається та не працює х

2023-04-09 21:15 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  /* opacity: 0;
код залиш, просто чомусь ти поставив на нього коментар

2023-04-09 21:16 UTC, Anastasiia505 commented on src/css/partials/subscribe.css
> +  stroke:var(--color-white);
svg з спрайта #icon-close-button оновили тепер він #icon-close. Зміни назву

2023-04-09 21:26 UTC, OleksandrLukomskyi commented on src/css/partials/subscribe.css
> +  /* opacity: 0;
> код залиш, просто чомусь ти поставив на нього коментар

то щоб бачити вікно. Виправив.

2023-04-10 09:14 UTC, NeoZLoy approved these changes
Молодец, хорошая работа!)
Небольшие поправки:
Нет медиправила для размера модалки при ширине экрана 1200px,
Стили текста в кнопке модалки не соответсвуют макету

2023-04-10 09:14 UTC, merged